config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "items#index"
  resources :items do
    resources :comments, only: :create
    resource :favorites, only: [:create, :destroy]
  end
  resources :users, only: :show do
    resource :follows, only: [:create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :item
  validates :content, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :item
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :following, class_name: "User"
  belongs_to :follower, class_name: "User"
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  has_many :favorites
  has_many :comments, dependent: :destroy
  has_one_attached :image
  validates :prefecture, presence: true
  validates :title, presence: true
  validates :introduce, presence: true
  validates :image, presence: true

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :nickname, presence: true
  has_many :items
  has_many :comments, dependent: :destroy

  has_many :active_follows, class_name: "Follow", foreign_key: :following_id
  has_many :followings, through: :active_follows, source: :follower

  has_many :passive_follows, class_name: "Follow", foreign_key: :follower_id
  has_many :followers, through: :passive_follows, source: :following
  has_many :favorites

  def followed_by?(user)
    follower = passive_follows.find_by(following_id: user.id)
    return follower.present?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :basic_auth

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(comment_params)
    if @comment.save
      redirect_to item_path(@comment.item)
    else
      @item = @comment.item
      @comments = @item.comments
      render "items/show"
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:content).merge(user_id: current_user.id, item_id: params[:item_id])
  end
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
  def create
    follow = current_user.active_follows.new(follower_id: params[:user_id])
    follow.save
    redirect_to root_path
  end

  def destroy
    follow = current_user.active_follows.find_by(follower_id: params[:user_id])
    follow.destroy
    redirect_to root_path
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @items = Item.includes(:user)
  end

  def new
    @item = Item.new
  end
  
  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to '/'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @item = Item.find(params[:id])
    @comment = Comment.new
    @comments = @item.comments.includes(:user)
  end

  def edit
    @item = Item.find(params[:id])
    unless @item.user_id == current_user.id
      redirect_to action: :index
    end
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to item_path
    else
      render :edit
    end
  end

  def destroy
    item = Item.find(params[:id])
    item.destroy
    redirect_to root_path
  end

  private
  def item_params
    params.require(:item).permit(:prefecture, :title, :introduce, :image).merge(user_id: current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  def show
    @user = User.find(params[:id])
    @items = @user.items
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/items/_form.html.erb
<%= form_with model: item, local: true do |f|%>
  <div class="field">
    <%= f.label :prefecture, "都道府県" %><br />
    <%= f.text_area :prefecture, class: :form__text, id:"item_prefecture" %>
  </div>

  <div class="field">
    <%= f.label :title, "名産品のタイトル" %><br />
    <%= f.text_field :title, class: :form__text, id:"item_title" %>
  </div>

  <div class="field">
    <%= f.label :introduce, "紹介文" %><br />
    <%= f.text_area :introduce, class: :form__text, id:"item_text" %>
  </div>

  <div class="field">
    <%= f.label :image, "名産品の画像" %><br />
    <%= f.file_field :image, id:"item_image" %>
  </div>

  <div class="actions">
    <%= f.submit "保存する", class: :form__btn  %>
  </div>
<% end %>

app/views/items/_item.html.erb
<div class="card">
  <%= link_to image_tag( item.image, class: :card__img ), item_path(item.id) if item.image.attached? %>
  <div class="card__body">
    <%= link_to item.title, item_path(item.id), class: :card__title%>
    <p class="card__summary">
      <%= item.introduce %>
    </p>
    <%= link_to "by #{item.user.nickname}", user_path(item.user), class: :card__user %>
  </div>
</div>

app/views/items/edit.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">名産品の編集</h2>
      <%= render partial: 'form', locals: {item: @item } %>
    </div>
  </div>
</div>

app/views/items/index.html.erb
<main class="main">
  <div class="inner">
    <% if user_signed_in? %>
      <div class="greeting">
        <%= "こんにちは、" %>
        <%= link_to "#{current_user.nickname}さん", user_path(current_user), class: :greeting__link%>
      </div>
    <% end %>
    <div class="card__wrapper">
      <%= render partial: 'item', collection: @items %>
    </div>
  </div>
</main>

app/views/items/new.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">新規名産品投稿</h2>
        <%= render partial: "form", locals: { item: @item } %>
    </div>
  </div>
</div>

app/views/items/show.html.erb
<main class="main">
  <div class="inner">
    <div class="item__wrapper">
      <p class="item__hedding">
        <%= @item.title %>
      </p>
      <%= link_to "by #{@item.user.nickname}", user_path(@item.user), class: :item__user %>
      <% if user_signed_in? && current_user.id == @item.user_id%>
        <div class="item__manage">
          <%= link_to "編集する", edit_item_path(@item.id), class: :item__btn %>
          <%= link_to "削除する", item_path(@item.id),data: { turbo_method: :delete }, class: :item__btn %>
        </div>
      <% end %>
      <div class="item__image">
        <%= image_tag @item.image %>
      </div>
      <div class="item__body">
        <div class="item__detail">
          <p class="detail__title">名産品のタイトル</p>
          <p class="detail__message">
            <%= @item.title %>
          </p>
        </div>
        <div class="item__detail">
          <p class="detail__title">紹介</p>
          <p class="detail__message">
            <%= @item.introduce %>
          </p>
        </div>
      </div>
      <div class="item__comments">
        <% if user_signed_in? %>
          <%= form_with model: [@item, @comment],local: true do |f|%>
            <div class="field">
              <%= f.label :content, "コメント" %><br />
              <%= f.text_field :content, id:"comment_content" %>
            </div>
            <div class="actions">
              <%= f.submit "送信する", class: :form__btn  %>
            </div>
          <% end %>
        <% end %>
        <ul class="comments_lists">
          <% @comments.each do |comment| %>
            <li class = "comments_list" >
              <%= comment.content %>
              <%= link_to (comment.user.nickname), "/users/#{comment.user_id}", class: :comment_user %>
            </li>
          <% end %>
        </ul>
        <div id="favorite-btn<%= @item.id %>">
        <% if user_signed_in? && @item.favorited_by?(current_user)%>
          <%=link_to "いいね済", item_favorites_path(@item.id), data: { turbo_method: :delete }, class: "item_favorites" %>
        <% else %>
          <%=link_to "いいねする", item_favorites_path(@item.id), data: { turbo_method: :post }, class: "item_favorites" %>
        <% end %>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Local-Speciality</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP:400,700,900&display=swap" rel="stylesheet">
  </head>

  <body>
    <header class="header">
      <div class="inner">
        <div class="nav">
          <div class="nav__left">
            <%= link_to "Local-Speciality", root_path, class: :logo %>
          </div>
          <% if user_signed_in? %>
            <div class="nav__right">
              <%= link_to "ログアウト", destroy_user_session_path, data: { turbo_method: :delete } , class: :nav__btn %>
              <%= link_to "New Item", new_item_path, class: :nav__btn %>
            </div>
          <% else %>
            <div class="nav__right">
              <%= link_to "ログイン", new_user_session_path, class: :nav__btn %>
              <%= link_to "新規登録", new_user_registration_path, class: :nav__btn %>
            </div>
          <% end %>
        </div>
      </div>
    </header>
    <%= yield %>
    <footer class="footer">
      <p class="copyright">Copyright © LOCAL SPECIALITY All rights reserved.</p>
    </footer>
  </body>
</html>

app/views/users/show.html.erb
<div class="main">
  <div class="inner">
    <div class="user__wrapper">
      <h2 class="page-heading">
        <%= "#{@user.nickname}さんの情報"%>
      </h2>
      <table class="table">
        <tbody>
          <tr>
            <th class="table__col1">名前</th>
            <td class="table__col2"><%= @user.nickname %></td>
          </tr>
        </tbody>
      </table>
      <h2>
      <% if current_user != @user %>
        <% if @user.followed_by?(current_user) %>
          <%=link_to "フォロー中", user_follows_path(@user.id),class: "btn", data: { turbo_method: :delete } %>
        <% else %>
          <%= link_to "フォローする", user_follows_path(@user.id), class: "btn", data: { turbo_method: :post } %>
        <% end %>
      <% end %>
      </h2>
      <h3>フォロー情報</h3>
      <h3>フォロー</h3>
      <% @user.followings.each do |user| %>
        <p class=“f-user”><%= link_to user.nickname, user_path(user.id) %></p>
      <% end %>
      <h3>フォロワー</h3>
      <% @user.followers.each do |user| %>
        <p class=“f-user”><%= link_to user.nickname, user_path(user.id) %></p>
      <% end %>

      <h2 class="page-heading">
        <%= "#{@user.nickname}さんのおすすめの名産品"%>
      </h2>
      <div class="user__card">
        <%= render partial: 'items/item', collection: @items %>
      </div>
    </div>
  </div>
</div>